# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 261f35946eda32d8a7a8d514452678dcf23c83ade5d22c0afc05f54774c6a7a8d203c154aac4b17d586643c317a132f6daf9ff1f08c6dca4646b7c79adfb3fa0

test:
  secret_key_base: e09399e0b936727326f7dde675ae34d6caa8bb936980117df282aedc409f39d1cdbf4d6d0c545eaa4f0f4c810812200e75501ea046b61a91f069f6817a29c747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
